[package]
name = "wasmtime-01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "19.0.1"
wasmtime-wasi = "19.0.1"
